### ISSUE TITLE
Assertion with PathBuilder::from_circle()

### ISSUE THREAD

**Issue by virtualritz** [linebender/tiny-skia#6]
When I use this I always get an assertion; regardless of what values I feed it. I'm using `master` btw.

A simple one is e.g.:

```Rust
let mut pixmap = Pixmap::new(256, 256).unwrap();

let mut dot_paint = Paint::default();
dot_paint.set_color(Color::from_rgba(0.8, 0.8, 0.8, 1.0).unwrap());
dot_paint.anti_alias = true;

let mut props = StrokeProps::default();
props.width = 1.0;

pixmap.fill_path(
    &PathBuilder::from_circle(10.0, 10.0, 5.0)
        .unwrap()
        .stroke(props)
        .unwrap(),
    &dot_paint,
);
```

```
thread 'main' panicked at 'assertion failed: outer1 > 0 && outer1 <= 1', /Users/moritz/.cargo/git/checkouts/tiny-skia-ff2529ae49675170/d07a5f9/src/stroker.rs:1466:5
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/moritz/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:505
   1: tiny_skia::stroker::quad_in_line
             at /Users/moritz/.cargo/git/checkouts/tiny-skia-ff2529ae49675170/d07a5f9/src/stroker.rs:1466
   2: tiny_skia::stroker::check_quad_linear
             at /Users/moritz/.cargo/git/checkouts/tiny-skia-ff2529ae49675170/d07a5f9/src/stroker.rs:1428
   3: tiny_skia::stroker::PathStroker::quad_to
             at /Users/moritz/.cargo/git/checkouts/tiny-skia-ff2529ae49675170/d07a5f9/src/stroker.rs:467
   4: tiny_skia::stroker::PathStroker::stroke_inner
             at /Users/moritz/.cargo/git/checkouts/tiny-skia-ff2529ae49675170/d07a5f9/src/stroker.rs:386
   5: tiny_skia::stroker::PathStroker::stroke
             at /Users/moritz/.cargo/git/checkouts/tiny-skia-ff2529ae49675170/d07a5f9/src/stroker.rs:296
   6: tiny_skia::path::Path::stroke
             at /Users/moritz/.cargo/git/checkouts/tiny-skia-ff2529ae49675170/d07a5f9/src/path.rs:88
   7: curve_widget::stroke_curve::{{closure}}
             at ./src/main.rs:69
   8: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /Users/moritz/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:203
   9: curve_widget::stroke_curve
             at ./src/main.rs:62
  10: curve_widget::main
             at ./src/main.rs:17
  11: core::ops::function::FnOnce::call_once
             at /Users/moritz/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
```

**Comment by RazrFalcon** [comment]
Yes, it's a known bug. I haven't investigated it yet.

PS: gradient transformation is also broken, I'm working on it too.

**Comment by virtualritz** [comment]
Ok, cool. Everything else is working nicely. :)
Is there any way I can reach you directly btw.? Rust Discord? Or email preferred?

**Comment by RazrFalcon** [comment]
I would prefer an email.

**Comment by virtualritz** [comment]
Can you confirm that the actual bug is trigged by `PathBuilder::quad_to()`? I just implemented my own circle `fn` and ran into the same assertion. Should've probably checked the `tiny-skia` sources 1st. :]

**Comment by RazrFalcon** [comment]
`quad_to` doesn't do anything. This is a stroker bug.

**Comment by RazrFalcon** [comment]
It was a very stupid mistake...

**Comment by virtualritz** [comment]
That was fast! Thanks heaps!!! :)
